# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 94cda23f50281d8f00b3cee3ff46c0b718d8b9a980c31057f2b5b0b9e40a4169a3c81a03c8c8d6b7e42577708d021f54638215c68386442fb05dc1cebbbcc49f

test:
  secret_key_base: 1503710c98afd9df37c9b54221fc038cff4d3774024620250e3b22ae51578181f65227b5ff850b107fe90f3b539398d9840c4c2d114ab6bb5b7c3bc24db9a58f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
